In [1]:
import numpy as np
from scipy import stats

In [10]:
x = [3,5,1,6,7,2,8,9,4]
y = [5,3,2,6,8,1,7,9,4]

In [16]:
def simpleSpearman(x,y)-> float:
    """
    Assuming np array as input
    """
    d = x - y
    n = len(x)
    rho = 1 - 6 * np.sum(np.square(d))/n/(n**2-1)
    return rho
x0 = np.array(x)
y0 = np.array(y)
print(simpleSpearman(x0,y0))

0.9


In [5]:
stats.spearmanr(x,y )

SpearmanrResult(correlation=-0.9, pvalue=0.0009430623223403293)

In [19]:
x = [3,5,1,6,7,2,8,9,4]
x = [(len(x)+1) - x[k] for k in range(len(x))] # Reverse the x ranking
y = [5,3,2,6,8,1,7,9,4]
print(stats.spearmanr(x,y ))
x0 = np.array(x)
y0 = np.array(y)
print(simpleSpearman(x0,y0))

SpearmanrResult(correlation=-0.9, pvalue=0.0009430623223403293)
-0.8999999999999999


In [3]:
rng = np.random.default_rng()
x2n = rng.standard_normal((100, 2))
y2n = rng.standard_normal((100, 2))
stats.spearmanr(x2n)

SpearmanrResult(correlation=-0.00876087608760876, pvalue=0.931061841564777)

In [4]:
stats.spearmanr(x2n[:,0], x2n[:,1])

SpearmanrResult(correlation=-0.00876087608760876, pvalue=0.931061841564777)

In [5]:
rho, pval = stats.spearmanr(x2n, y2n)
print('rho = \n',rho)
print('pval = \n',pval)

rho = 
 [[ 1.         -0.00876088 -0.1219922  -0.0780078 ]
 [-0.00876088  1.         -0.07627963  0.20618062]
 [-0.1219922  -0.07627963  1.          0.15810381]
 [-0.0780078   0.20618062  0.15810381  1.        ]]
pval = 
 [[0.         0.93106184 0.22662196 0.44044198]
 [0.93106184 0.         0.45066551 0.0395851 ]
 [0.22662196 0.45066551 0.         0.11616891]
 [0.44044198 0.0395851  0.11616891 0.        ]]


In [6]:
rho, pval = stats.spearmanr(x2n.T, y2n.T, axis=1)
print('rho = \n',rho)
print('pval = \n',pval)

rho = 
 [[ 1.         -0.00876088 -0.1219922  -0.0780078 ]
 [-0.00876088  1.         -0.07627963  0.20618062]
 [-0.1219922  -0.07627963  1.          0.15810381]
 [-0.0780078   0.20618062  0.15810381  1.        ]]
pval = 
 [[0.         0.93106184 0.22662196 0.44044198]
 [0.93106184 0.         0.45066551 0.0395851 ]
 [0.22662196 0.45066551 0.         0.11616891]
 [0.44044198 0.0395851  0.11616891 0.        ]]


In [7]:
stats.spearmanr(x2n, y2n, axis=None)
print('rho = \n',rho)
print('pval = \n',pval)

rho = 
 [[ 1.         -0.00876088 -0.1219922  -0.0780078 ]
 [-0.00876088  1.         -0.07627963  0.20618062]
 [-0.1219922  -0.07627963  1.          0.15810381]
 [-0.0780078   0.20618062  0.15810381  1.        ]]
pval = 
 [[0.         0.93106184 0.22662196 0.44044198]
 [0.93106184 0.         0.45066551 0.0395851 ]
 [0.22662196 0.45066551 0.         0.11616891]
 [0.44044198 0.0395851  0.11616891 0.        ]]


In [8]:
stats.spearmanr(x2n.ravel(), y2n.ravel())
print('rho = \n',rho)
print('pval = \n',pval)

rho = 
 [[ 1.         -0.00876088 -0.1219922  -0.0780078 ]
 [-0.00876088  1.         -0.07627963  0.20618062]
 [-0.1219922  -0.07627963  1.          0.15810381]
 [-0.0780078   0.20618062  0.15810381  1.        ]]
pval = 
 [[0.         0.93106184 0.22662196 0.44044198]
 [0.93106184 0.         0.45066551 0.0395851 ]
 [0.22662196 0.45066551 0.         0.11616891]
 [0.44044198 0.0395851  0.11616891 0.        ]]


In [9]:
rng = np.random.default_rng()
xint = rng.integers(10, size=(100, 2))
stats.spearmanr(xint)

SpearmanrResult(correlation=0.06160900820178981, pvalue=0.5425753687396238)

In [12]:
import pandas as pd
import numpy as np
X=pd.Series([3,5,1,6,7,2,8,9,4])
Y=pd.Series([5,3,2,6,8,1,7,9,4])
rho = X.corr(Y,method='spearman')
print(rho)


0.9
