In [1]:
import torch

(tensor(5.), tensor(6.), tensor(1.5000), tensor(9.))

In [2]:
# scalar
x = torch.tensor(3.0)
y = torch.tensor(2.0)

print(x + y, x * y, x / y, x**y)

# vector
x = torch.arange(4)
print(x,x.shape)

tensor(5.) tensor(6.) tensor(1.5000) tensor(9.)
tensor([0, 1, 2, 3]) torch.Size([4])


尽管单个向量的默认方向是列向量，但在表示表格数据集的矩阵中， 将每个数据样本作为矩阵中的行向量更为常见。 后面的章节将讲到这点，这种约定将支持常见的深度学习实践。 例如，沿着张量的最外轴，我们可以访问或遍历小批量的数据样本。

In [3]:
# Matrix
A = torch.arange(20).reshape(5, 4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [4]:
# Tensor
X = torch.arange(24).reshape(2, 3, 4)
print(f'X = {X}')

X = tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])


In [8]:
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = A.clone()  # 通过分配新内存，将A的一个副本分配给B. Note: not copy()!
print(A, "\n", A + B)
print(id(A),id(B))

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]]) 
 tensor([[ 0.,  2.,  4.,  6.],
        [ 8., 10., 12., 14.],
        [16., 18., 20., 22.],
        [24., 26., 28., 30.],
        [32., 34., 36., 38.]])
2293499591952 2293499591552


In [7]:
# Hardmard product
print(A * B)

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])


In [10]:
# Broadcasting
# 将张量乘以或加上一个标量不会改变张量的形状，其中张量的每个元素都将与标量相加或相乘。
a = 2
X = torch.arange(24).reshape(2, 3, 4)
a + X, (a * X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

In [11]:
# Reduction
x = torch.arange(4, dtype=torch.float32)
print(x, x.sum())

tensor([0., 1., 2., 3.]) tensor(6.)


针对高阶张量，默认情况下，调用求和函数会沿所有的轴降低张量的维度，使它变为一个标量。我们还可以指定张量沿哪一个轴来通过求和降低维度。 以矩阵为例，为了通过求和所有行的元素来降维（轴0），可以在调用函数时指定axis=0。 由于输入矩阵沿0轴降维以生成输出向量，因此输入轴0的维数在输出形状中消失。
 
 其实可以看做两个步骤：
 
 (1) 首先沿指定轴进行reduction运算将该轴的长度变为1
 
 (2) 其次，通过类似于numpy的squeeze()操作将该长度为1的轴消除掉

In [19]:
x = torch.arange(24).reshape(4,2,3)
print(x.sum(), x.sum([0,1]), x.sum([0,1,2]))
print(x.sum(axis=0))
print(x.sum(axis=1))
print(x.sum(axis=2))

tensor(276) tensor([ 84,  92, 100]) tensor(276)
tensor([[36, 40, 44],
        [48, 52, 56]])
tensor([[ 3,  5,  7],
        [15, 17, 19],
        [27, 29, 31],
        [39, 41, 43]])
tensor([[ 3, 12],
        [21, 30],
        [39, 48],
        [57, 66]])


In [14]:
import numpy as np
x = np.arange(24).reshape(4,2,3)
print(x.sum(axis=0))
print(x.sum(axis=1))
print(x.sum(axis=2))

[[36 40 44]
 [48 52 56]]
[[ 3  5  7]
 [15 17 19]
 [27 29 31]
 [39 41 43]]
[[ 3 12]
 [21 30]
 [39 48]
 [57 66]]


In [21]:
x = np.arange(24).reshape(4,1,-1)
print(x)
print(x.squeeze())

[[[ 0  1  2  3  4  5]]

 [[ 6  7  8  9 10 11]]

 [[12 13 14 15 16 17]]

 [[18 19 20 21 22 23]]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [25]:
x = torch.arange(24).reshape(4,2,3)
print(x.mean(dtype=float))
print(x.sum()/x.numel())

tensor(11.5000, dtype=torch.float64)
tensor(11.5000)


In [37]:
# 可以在指定进行reduction的轴后用keepdims=True来要求经过mean()或者sum()后保持轴
A = torch.arange(24).reshape(4,-1)
print(A.sum(axis=1, keepdims=True))
print(A.sum(axis=1, keepdims=False))

tensor([[ 15],
        [ 51],
        [ 87],
        [123]])
tensor([ 15,  51,  87, 123])


In [35]:
A = torch.arange(24).reshape(4,-1)
sum_A = A.sum(axis=1, keepdims=True)
sum_A

tensor([[ 15],
        [ 51],
        [ 87],
        [123]])

In [40]:
print(A.cumsum(axis=0))
print(A.cumsum(axis=1))

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  8, 10, 12, 14, 16],
        [18, 21, 24, 27, 30, 33],
        [36, 40, 44, 48, 52, 56]])
tensor([[  0,   1,   3,   6,  10,  15],
        [  6,  13,  21,  30,  40,  51],
        [ 12,  25,  39,  54,  70,  87],
        [ 18,  37,  57,  78, 100, 123]])


In [43]:
# dot-product
y = torch.ones(4, dtype = torch.float32)
x = torch.arange(4, dtype = torch.float32)
x, y, torch.dot(x, y), torch.sum(x * y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.), tensor(6.))

In [49]:
# matrix-vector product
A = torch.arange(24, dtype = torch.float32).reshape(4,-1).T
x = torch.arange(4, dtype = torch.float32)
print(A.shape, x.shape, torch.mv(A, x))

torch.Size([6, 4]) torch.Size([4]) tensor([ 84.,  90.,  96., 102., 108., 114.])


In [51]:
# matrix-matrix product
B = torch.ones(4, 3)
C = torch.mm(A, B)
print(C , C.shape)

tensor([[36., 36., 36.],
        [40., 40., 40.],
        [44., 44., 44.],
        [48., 48., 48.],
        [52., 52., 52.],
        [56., 56., 56.]]) torch.Size([6, 3])


In [54]:
# L2 Norm
x = torch.arange(4, dtype = torch.float32)
print(x.norm(), torch.sqrt(torch.sum(x * x)))

# L1 norm
print(x.abs().sum())

tensor(3.7417) tensor(3.7417)
tensor(6.)


In [55]:
# Frobenius norm
A = torch.arange(24, dtype = torch.float32).reshape(4,-1)
print(torch.sqrt(torch.sum(A * A)))

tensor(65.7571)
